### PR TITLE
Target windows 7

### LINKED ISSUE #245: Running compiled build: CreateFile2 could not be located in kernel32.dll
The compiled build can't run on my computer; I'm unsure what has caused this.

After launching, a popup dialog says:

> #### amulet_app.exe - Entry Point Not Found
> The procedure entrypoint CreateFile2 could not be located in the dynamic link library kernel32.dll.

Terminal output:

<details>

```
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes\__init__.py", line 364, in __init__
OSError: [WinError 127] The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\__main__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet_map_editor\api\framework\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet_map_editor\api\framework\amulet_ui.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\level\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\level\load.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\api\level\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\api\level\base_level\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\api\level\base_level\base_level.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\api\level\base_level\chunk_manager.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\api\cache.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\libs\leveldb\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "amulet\libs\leveldb\leveldb.py", line 21, in <module>
  File "ctypes\__init__.py", line 442, in LoadLibrary
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'E:\\LNNSoftware\\Amulet\\amulet\\libs\\leveldb\\LevelDB-MCPE-64.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[15564] Failed to execute script __main__
```

</details>

I'm running version 0.8.2 on Windows 7 (x64).

### PR DESCRIPTION
**Pull request by gentlegiantJGC**
Target windows 7 to try to fix https://github.com/Amulet-Team/Amulet-Map-Editor/issues/245

### CODE REVIEW

**Comment by Some14u** [comment]
perhaps this could help: https://stackoverflow.com/questions/25018115/libcurl-the-procedure-entrypoint-createfile2-could-not-be-located

**Comment by gentlegiantJGC** [comment]
I think if I add this line to both the zlib and leveldb `CMakeLists.txt` files it works and doesn't include the `CreateFile2` reference.
`add_definitions(-D_WIN32_WINNT=0x0601)`
I am trying to work out how to specify this in the command line so that I don't need to modify that file

**Comment by gentlegiantJGC** [comment]
@Some14u if you are running windows 7 can you test if this works.
https://github.com/Amulet-Team/leveldb-mcpe/releases/tag/0.7a5

**Comment by Some14u** [comment]
Okay, should i build it myself from this repo?
I'm not sure what to do with LevelDB-MCPE-32.dll, libleveldb.dylib, and libleveldb.so
Found a place for LevelDB-MCPE-64.dll though.

**Comment by Some14u** [comment]
Oh, updated LevelDB-MCPE-64.dll and it works. Great.

**Comment by gentlegiantJGC** [comment]
Great thanks

**Pull request merged**
